### ISSUE TITLE
Forecast model crash when converting date into float

### ISSUE THREAD

**Issue by xzdandy** [georgia-tech-db/evadb#1065]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

In the [Colab notebook](https://colab.research.google.com/drive/1B5ej5A2gQJZqKk3W3SmSSaqjVNWsOqi8?usp=sharing), we tried to use the forecast capability of EvaDB to train a home price forecasting model.  The below query

```
cursor.query("""
  CREATE FUNCTION IF NOT EXISTS HomeSaleForecast FROM
    (
      SELECT saledate, ma 
      FROM postgres_data.home_sales 
      WHERE type = "house" AND bedrooms = 2
    )
  TYPE Forecasting
  PREDICT 'ma'
  TIME 'saledate'
  FREQUENCY 'M';
""").df()
```
failed with the follow error message:
```
ERROR:evadb.utils.logging_manager:could not convert string to float: '30/09/2007'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/evadb/executor/plan_executor.py", line 178, in execute_plan
    yield from output
  File "/usr/local/lib/python3.10/dist-packages/evadb/executor/create_function_executor.py", line 316, in exec
    ) = self.handle_forecasting_function()
  File "/usr/local/lib/python3.10/dist-packages/evadb/executor/create_function_executor.py", line 217, in handle_forecasting_function
    model.fit(data)
  File "/usr/local/lib/python3.10/dist-packages/statsforecast/core.py", line 878, in fit
    self._prepare_fit(df, sort_df)
  File "/usr/local/lib/python3.10/dist-packages/statsforecast/core.py", line 833, in _prepare_fit
    df_process = DataFrameProcessing(df, sort_df)
  File "/usr/local/lib/python3.10/dist-packages/statsforecast/core.py", line 459, in __init__
    self.__call__()
  File "/usr/local/lib/python3.10/dist-packages/statsforecast/core.py", line 476, in __call__
    [
  File "/usr/local/lib/python3.10/dist-packages/statsforecast/core.py", line 477, in <listcomp>
    self.value_array[name].astype(float)
ValueError: could not convert string to float: '30/09/2007'
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xzdandy** [comment]
Hi @americast, is converting the `date` column into `float` expected for statsforecast framework? Thanks!

**Comment by xzdandy** [comment]
We will revamp forecast support in #1081
