### ISSUE TITLE
bug: failure in create table using select query results in following unexpected error for native tables

### ISSUE THREAD

**Issue by gaurav274** [georgia-tech-db/evadb#1220]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

Traceback (most recent call last):
  File "/home/gkakkar7/VAST/evadb/evadb_310/lib/python3.10/site-packages/evadb/executor/plan_executor.py", line 180, in execute_plan
    output = execution_tree.exec()
  File "/home/gkakkar7/VAST/evadb/evadb_310/lib/python3.10/site-packages/evadb/executor/create_executor.py", line 75, in exec
    storage_engine.drop(catalog_entry)
AttributeError: 'NativeStorageEngine' object has no attribute 'drop'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by gaurav274** [comment]
Fixed with #1208
