### ISSUE TITLE
bug: create table into a native storage using select query fails with following error

### ISSUE THREAD

**Issue by gaurav274** [georgia-tech-db/evadb#1221]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

```
09-26-2023 02:22:43 ERROR [native_storage_engine:native_storage_engine.py:read:0201] Failed to read the table evadb_StargazerList in data source sqlite_data with exception tuple indices must be integers or slices, not str
Traceback (most recent call last):
  File "/home/gkakkar7/VAST/evadb/evadb_310/lib/python3.10/site-packages/evadb/storage/native_storage_engine.py", line 193, in read
    data_batch.append(_deserialize_sql_row(row, ordered_columns))
  File "/home/gkakkar7/VAST/evadb/evadb_310/lib/python3.10/site-packages/evadb/storage/native_storage_engine.py", line 95, in _deserialize_sql_row
    if col.type == ColumnType.NDARRAY and isinstance(sql_row[col.name], bytes):
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 48, in sqlalchemy.cyextension.resultproxy.BaseRow.__getitem__
TypeError: tuple indices must be integers or slices, not str
09-26-2023 02:22:43 ERROR [plan_executor:plan_executor.py:execute_plan:0186] Failed to read the table evadb_StargazerList in data source sqlite_data with exception tuple indices must be integers or slices, not str
Traceback (most recent call last):
  File "/home/gkakkar7/VAST/evadb/evadb_310/lib/python3.10/site-packages/evadb/storage/native_storage_engine.py", line 193, in read
    data_batch.append(_deserialize_sql_row(row, ordered_columns))
  File "/home/gkakkar7/VAST/evadb/evadb_310/lib/python3.10/site-packages/evadb/storage/native_storage_engine.py", line 95, in _deserialize_sql_row
    if col.type == ColumnType.NDARRAY and isinstance(sql_row[col.name], bytes):
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 48, in sqlalchemy.cyextension.resultproxy.BaseRow.__getitem__
TypeError: tuple indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gkakkar7/VAST/evadb/evadb_310/lib/python3.10/site-packages/evadb/executor/plan_executor.py", line 182, in execute_plan
    yield from output
  File "/home/gkakkar7/VAST/evadb/evadb_310/lib/python3.10/site-packages/evadb/executor/project_executor.py", line 44, in exec
    for batch in child_executor.exec(**kwargs):
  File "/home/gkakkar7/VAST/evadb/evadb_310/lib/python3.10/site-packages/evadb/executor/seq_scan_executor.py", line 40, in exec
    for batch in child_executor.exec(**kwargs):
  File "/home/gkakkar7/VAST/evadb/evadb_310/lib/python3.10/site-packages/evadb/storage/native_storage_engine.py", line 202, in read
    raise Exception(err_msg)
Exception: Failed to read the table evadb_StargazerList in data source sqlite_data with exception tuple indices must be integers or slices, not str
❗️ EvaDB Session ended with an error: Failed to read the table evadb_StargazerList in data source sqlite_data with exception tuple indices must be integers or slices, not str
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by gaurav274** [comment]
The bug was incorrectly reported. Cannot be reproduced!
