### ISSUE TITLE
'>=' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by onefanwu** [georgia-tech-db/evadb#1357]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

```
ERROR [plan_executor:plan_executor.py:execute_plan:0179] '>=' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
  File ".../evadb/executor/plan_executor.py", line 175, in execute_plan
    yield from output
  File ".../evadb/executor/exchange_executor.py", line 101, in exec
    raise res
evadb.executor.executor_utils.ExecutorError: '>=' not supported between instances of 'int' and 'str'
```

When I execute the following queries, I get the above error, if ray is not turned on it executes fine.
```sql
SET ray="True";
SET gpu_ids="[0, 1, 2, 3, 4, 5, 6, 7]";
SET batch_mem_size="300000";

DROP TABLE IF EXISTS NightStreet;

LOAD VIDEO 'benchmark/datasets/video/night-street.mp4'
INTO NightStreet;

DROP TABLE IF EXISTS Yolo;

CREATE FUNCTION IF NOT EXISTS Yolo
TYPE  ultralytics
MODEL 'benchmark/models/yolov8x.pt';

SELECT id, Yolo(data).labels
FROM NightStreet
WHERE ['person', 'car'] <@ Yolo(data).labels
LIMIT 5;

```

### Environment

- EvaDB v0.3.8

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by onefanwu** [comment]
I have solved it, I was incorrectly using str values for the assignment when setting ray and batch_mem_size.
