### ISSUE TITLE
eva-decord not supported for arm linux

### ISSUE THREAD

**Issue by yulinzou** [georgia-tech-db/evadb#1453]
### Search before asking

- [X] I have searched the EvaDB [issues](https://github.com/georgia-tech-db/eva/issues) and found no similar bug report.

### Bug

Failed to install eva-decord for cursor.query("LOAD VIDEO 'russia_ukraine.mp4' INTO VIDEOS").df()

```
Traceback (most recent call last):
  File "/users/yulin001/run_evadb.py", line 25, in <module>
    cursor.query("LOAD VIDEO 'russia_ukraine.mp4' INTO VIDEOS").df()
  File "/users/yulin001/evadb-venv/lib/python3.9/site-packages/evadb/interfaces/relational/relation.py", line 123, in df
    batch = self.execute(drop_alias=drop_alias)
  File "/users/yulin001/evadb-venv/lib/python3.9/site-packages/evadb/interfaces/relational/relation.py", line 141, in execute
    result = execute_statement(self._evadb, self._query_node.copy())
  File "/users/yulin001/evadb-venv/lib/python3.9/site-packages/evadb/server/command_handler.py", line 53, in execute_statement
    batch_list = list(output)
  File "/users/yulin001/evadb-venv/lib/python3.9/site-packages/evadb/executor/plan_executor.py", line 183, in execute_plan
    raise ExecutorError(e)
evadb.executor.executor_utils.ExecutorError: Could not import decord python package.
                Please install it with `pip install eva-decord`.
```

```
pip install eva-decord
ERROR: Could not find a version that satisfies the requirement eva-decord (from versions: none)
ERROR: No matching distribution found for eva-decord
```

### Environment

- EvaDB: v0.3.9
- Ubuntu: 18.04
- Python: 3.9.19
- CPU: arm64
- GPU: No

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by yulinzou** [comment]
Followed the [tutorial](https://evadb.readthedocs.io/en/stable/source/usecases/question-answering.html), failed to execute `cursor.query("LOAD VIDEO 'russia_ukraine.mp4' INTO VIDEOS").df()`
